[versions]
springboot = "3.0.5"
springcloud = "2022.0.1"
springcloudalibaba = "2022.0.0.0-RC2"
springdoc-openapi-ui = "1.7.0"
commons-lang3 = "3.12.0"
fastjson2 = "2.0.29"


[libraries]
springdoc-openapi-ui = {group = "org.springdoc",name="springdoc-openapi-ui", version.ref = "springdoc-openapi-ui" }
commons-lang3 = {group = "org.apache.commons",name="commons-lang3", version.ref = "commons-lang3" }
fastjson2 = {group = "com.alibaba.fastjson2",name="fastjson2", version.ref = "fastjson2" }

[plugins]