[versions]
# 统一依赖管理
springboot = "3.1.0"
springcloud = "2022.0.3"
springcloudalibaba = "2022.0.0.0-RC2"
# Web 相关
springdoc-openapi-ui = "1.7.0"
# DB 相关
# RPC 相关
# 监控相关
# 工具类相关
lombok = "1.18.26"
# 第三方云服务相关

[libraries]
# Web 相关
springdoc-openapi-ui = {group = "org.springdoc",name="springdoc-openapi-ui", version.ref = "springdoc-openapi-ui" }

[plugins]
# 环境
spring-boot-gradle-plugin = { id = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springboot"}